config/routes.rb
SampleApp::Application.routes.draw do

  resources :consumption_reports, only: [:index] do
    collection do
      get 'fmu76'
    end
  end

  resources :vehicles
  resources :vehicle_models
  resources :warehouses
  resources :skus
  resources :inventory_models
  resources :groups
  resources :users
  resources :storages
  resources :user_uploads, only: [:new, :create]
  resources :inventory_reserves do
    member do
      get 'create_order'
    end
  end

  resources :inventory_operations do
    member do
      post 'apply'
    end
  end

  resources :receive_inventories, except: [:index, :destroy]
  resources :write_off_inventories, except: [:index, :destroy] do
    member do
      get 'vehicle_picker'
    end
  end

  resources :take_inventories, except: [:index, :destroy]
  resources :release_inventories, except: [:index, :destroy]

  resource :user_sessions, only: [:create]
  resources :users

  resources :inventories

  resources :measures
  resources :measuring_units
  resources :organizations
  resources :inventory_orders do
    member do
      get 'm11'
      get 'receive'
    end
  end
  resources :barcodes, only: [:show] do
    member do
      get 'draw'
      get 'print'
    end
  end
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  namespace :api, defaults: {format: 'json'} do

    resources :users, only: [:index, :show] do
      collection do
        post 'import'
      end
    end

    resources :inventories do
      collection do
        get 'available_amounts'
        get 'reserved_amounts'
        post 'reserve'
        post 'release'
      end
    end

    resources :inventory_models, only: [:index, :show]
    resources :measuring_units, only: [:index, :show]
    resources :skus, only: [:index, :show]
    resources :storages, only: [:index]
  end

  root to: "inventory_operations#index"

end

app/models/inventory_model.rb
class InventoryModel < ActiveRecord::Base
  attr_accessible :description, :title

  has_many :skus, foreign_key: 'model_id'

  validates :title, presence: true, uniqueness: true

  def to_s
    self.title
  end
end

app/controllers/api/inventory_models_controller.rb
module Api
  class InventoryModelsController < ApiController
    def index
      @inventory_models = InventoryModel.order(:title)
    end

    def show
      @inventory_model = InventoryModel.find params[:id]
    end
  end
end

app/controllers/inventory_models_controller.rb
class InventoryModelsController < ApplicationController

  before_filter do
    require_user
  end

  before_filter only: [:show, :edit, :update, :destroy] do
    @inventory_model = InventoryModel.find params[:id]
  end

  before_filter only: [:new, :create] do
    @inventory_model = InventoryModel.new
  end


  # GET /inventory_models
  def index
    @inventory_models = InventoryModel.page(current_page).order(sort_order('title asc'))
  end

  # POST /inventory_models
  def create
    create_or_update
  end


  # PUT /inventory_models/1
  def update
    create_or_update
  end

  # DELETE /inventory_models/1
  def destroy
    @inventory_model.destroy
    flash[:alert] = t('helpers.notices.destroy.success')
    redirect_to inventory_models_url
  end


  def valid_sort_columns
    %w(title)
  end

  private
    def create_or_update
      @inventory_model.attributes = params[:inventory_model]

      if @inventory_model.save
        redirect_to @inventory_model, notice: t('helpers.notices.saved')
      else
        render action: @inventory_model.new_record? ? 'new' : 'edit'
      end
    end
end

app/helpers/inventory_models_helper.rb
module InventoryModelsHelper
end

app/views/inventory_models/_form.html.erb
<%= form_for @inventory_model, html: {class: 'form-horizontal'} do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :title, "#{t('inventory_models.attrs.title')}:", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, "#{t('inventory_models.attrs.description')}:", class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, class: 'text_area' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit t('helpers.links.ok'), class: 'btn btn-primary' %>
    <%= link_to t('helpers.links.cancel'), :back, class: 'btn' %>
  </div>
<% end %>

app/views/inventory_models/_inventory_model.html.erb
<tr data-link="<%= inventory_model_path(inventory_model) %>">
  <td><%= inventory_model.title %></td>
  <td><%= inventory_model.description %></td>
</tr>

app/views/inventory_models/edit.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
  <p class="muted"><%= t('helpers.notices.edit') %></p>
</div>
<%= render partial: 'form' %>

app/views/inventory_models/index.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sortable :title, t('inventory_models.attrs.title') %></th>
      <th><%= sortable :description, t('inventory_models.attrs.description') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render(partial: 'inventory_model', collection: @inventory_models) || render('shared/empty', colspan: 2) %>
  </tbody>
</table>

<%= will_paginate(@inventory_models) -%>

<%= link_to t('helpers.links.new'), new_inventory_model_path, class: 'btn btn-primary' %>

app/views/inventory_models/new.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
  <p class="muted"><%= t('helpers.notices.new') %></p>
</div>
<%= render partial: 'form' %>

app/views/inventory_models/show.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
</div>
<div class="form-horizontal">
  <div class="control-group">
    <div class='control-label'><%= t('inventory_models.attrs.title') %>:</div>
    <div class="controls">
      <span><%= @inventory_model.title %></span>
    </div>
  </div>
    <div class="control-group">
      <div class='control-label'><%= t('inventory_models.attrs.description') %>:</div>
      <div class="controls">
        <span><%= @inventory_model.description %></span>
      </div>
    </div>
    <div class="form-actions">
      <%= link_to t('helpers.links.index'), inventory_models_path(params: session[:index_params]), class: 'btn' %>
      <%= link_to t('helpers.links.edit'), edit_inventory_model_path(@inventory_model), class: 'btn' %>
      <%= link_to t('helpers.links.destroy'), inventory_model_path(@inventory_model), method: 'delete',
                  data: {confirm: t('helpers.confirmations.destroy')},
                  class: 'btn btn-danger' %>
    </div>
</div>