config/routes.rb
SampleApp::Application.routes.draw do

  resources :consumption_reports, only: [:index] do
    collection do
      get 'fmu76'
    end
  end

  resources :vehicles
  resources :vehicle_models
  resources :warehouses
  resources :skus
  resources :inventory_models
  resources :groups
  resources :users
  resources :storages
  resources :user_uploads, only: [:new, :create]
  resources :inventory_reserves do
    member do
      get 'create_order'
    end
  end

  resources :inventory_operations do
    member do
      post 'apply'
    end
  end

  resources :receive_inventories, except: [:index, :destroy]
  resources :write_off_inventories, except: [:index, :destroy] do
    member do
      get 'vehicle_picker'
    end
  end

  resources :take_inventories, except: [:index, :destroy]
  resources :release_inventories, except: [:index, :destroy]

  resource :user_sessions, only: [:create]
  resources :users

  resources :inventories

  resources :measures
  resources :measuring_units
  resources :organizations
  resources :inventory_orders do
    member do
      get 'm11'
      get 'receive'
    end
  end
  resources :barcodes, only: [:show] do
    member do
      get 'draw'
      get 'print'
    end
  end
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  namespace :api, defaults: {format: 'json'} do

    resources :users, only: [:index, :show] do
      collection do
        post 'import'
      end
    end

    resources :inventories do
      collection do
        get 'available_amounts'
        get 'reserved_amounts'
        post 'reserve'
        post 'release'
      end
    end

    resources :inventory_models, only: [:index, :show]
    resources :measuring_units, only: [:index, :show]
    resources :skus, only: [:index, :show]
    resources :storages, only: [:index]
  end

  root to: "inventory_operations#index"

end

app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base
  attr_accessible :description, :title, :section_count

  SECTION_COUNT_RANGE = 1..4

  validates_presence_of :title, :section_count
  validates_uniqueness_of :title
  validates :section_count, numericality: {only_integer: true}, inclusion: SECTION_COUNT_RANGE


  after_initialize do
    self.section_count ||= 1 if self.new_record?
  end

  def multiple_unit?
    (self.section_count > 1) if self.section_count
  end

  def section_indexes
    (0..self.section_count - 1).map { |i| VehicleSectionIndex.new(i, self.multiple_unit?) } if self.section_count
  end

  def to_s
    self.title
  end
end

app/controllers/vehicle_models_controller.rb
class VehicleModelsController < ApplicationController
  before_filter do
    require_user
  end

  # GET /vehicle_models
  # GET /vehicle_models.json
  def index
    @vehicle_models = VehicleModel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicle_models }
    end
  end

  # GET /vehicle_models/1
  # GET /vehicle_models/1.json
  def show
    @vehicle_model = VehicleModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle_model }
    end
  end

  # GET /vehicle_models/new
  # GET /vehicle_models/new.json
  def new
    @vehicle_model = VehicleModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle_model }
    end
  end

  # GET /vehicle_models/1/edit
  def edit
    @vehicle_model = VehicleModel.find(params[:id])
  end

  # POST /vehicle_models
  # POST /vehicle_models.json
  def create
    @vehicle_model = VehicleModel.new(params[:vehicle_model])

    respond_to do |format|
      if @vehicle_model.save
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully created.' }
        format.json { render json: @vehicle_model, status: :created, location: @vehicle_model }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicle_models/1
  # PUT /vehicle_models/1.json
  def update
    @vehicle_model = VehicleModel.find(params[:id])

    respond_to do |format|
      if @vehicle_model.update_attributes(params[:vehicle_model])
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_models/1
  # DELETE /vehicle_models/1.json
  def destroy
    @vehicle_model = VehicleModel.find(params[:id])
    @vehicle_model.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicle_models_helper.rb
module VehicleModelsHelper
end

app/views/vehicle_models/_form.html.erb
<%= form_for @vehicle_model, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
    <div class="control-group">
      <%= f.label :section_count, class: 'control-label' %>
      <div class="controls">
        <%= f.number_field :section_count, in: VehicleModel::SECTION_COUNT_RANGE, class: 'number_field' %>
      </div>
    </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, class: 'text_area' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit t('helpers.links.ok'), class: 'btn btn-primary' %>
    <%= link_to t('helpers.links.cancel'), @vehicle_model, class: 'btn' %>
  </div>
<% end %>

app/views/vehicle_models/edit.html.erb
<%- model_class = VehicleModel -%>
<div class="page-header">
  <h3><%= t '.title', default: '%{model}', model: model_class.model_name.human.titleize %></h3>
  <p class="muted"><%= t('helpers.titles.edit') %></p>
</div>
<%= render partial: 'form' %>

app/views/vehicle_models/index.html.erb
<%- model_class = VehicleModel -%>
<div class="page-header">
  <h3><%= t '.title', default: model_class.model_name.human(count: 2) %></h3>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name('title') %></th>
      <th><%= model_class.human_attribute_name('section_count') %></th>
      <th><%= model_class.human_attribute_name('description') %></th>
    </tr>
  </thead>
  <tbody>
    <% @vehicle_models.each do |vehicle_model| %>
      <tr data-link="<%= vehicle_model_path(vehicle_model) %>">
        <td><%= vehicle_model.title %></td>
        <td><%= vehicle_model.section_count %></td>
        <td><%= vehicle_model.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('helpers.links.new'), new_vehicle_model_path, class: 'btn btn-primary' %>

app/views/vehicle_models/new.html.erb
<%- model_class = VehicleModel -%>
<div class="page-header">
  <h3><%= t '.title', default: '%{model}', model: model_class.model_name.human.titleize %></h3>
  <p class="muted"><%= t('helpers.titles.new') %></p>
</div>
<%= render partial: 'form' %>

app/views/vehicle_models/show.html.erb
<%- model_class = VehicleModel -%>
<div class="page-header">
  <h3><%= t '.title', default: model_class.model_name.human.titleize %></h3>
</div>

<div id="vehicle_model" class="form-horizontal">

  <div class="control-group">
    <div class="control-label"><%= model_class.human_attribute_name('title') %>:</div>
    <div class="controls">
      <span><%= @vehicle_model.title %></span>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label"><%= model_class.human_attribute_name('section_count') %>:</div>
    <div class="controls">
      <span><%= @vehicle_model.section_count %></span>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label"><%= model_class.human_attribute_name('description') %>:</div>
    <div class="controls">
      <span><%= @vehicle_model.description %></span>
    </div>
  </div>

  <div class="form-actions">
    <%= link_to t('helpers.links.index'), vehicle_models_path, class: 'btn' %>
    <%= link_to t('helpers.links.edit'), edit_vehicle_model_path(@vehicle_model), class: 'btn' %>
    <%= link_to t('helpers.links.destroy'), vehicle_model_path(@vehicle_model),
                method: 'delete',
                data: {confirm: t('helpers.confirmations.destroy', default: 'Are you sure?')},
                class: 'btn btn-danger' %>
  </div>
</div>