config/routes.rb
SampleApp::Application.routes.draw do

  resources :consumption_reports, only: [:index] do
    collection do
      get 'fmu76'
    end
  end

  resources :vehicles
  resources :vehicle_models
  resources :warehouses
  resources :skus
  resources :inventory_models
  resources :groups
  resources :users
  resources :storages
  resources :user_uploads, only: [:new, :create]
  resources :inventory_reserves do
    member do
      get 'create_order'
    end
  end

  resources :inventory_operations do
    member do
      post 'apply'
    end
  end

  resources :receive_inventories, except: [:index, :destroy]
  resources :write_off_inventories, except: [:index, :destroy] do
    member do
      get 'vehicle_picker'
    end
  end

  resources :take_inventories, except: [:index, :destroy]
  resources :release_inventories, except: [:index, :destroy]

  resource :user_sessions, only: [:create]
  resources :users

  resources :inventories

  resources :measures
  resources :measuring_units
  resources :organizations
  resources :inventory_orders do
    member do
      get 'm11'
      get 'receive'
    end
  end
  resources :barcodes, only: [:show] do
    member do
      get 'draw'
      get 'print'
    end
  end
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  namespace :api, defaults: {format: 'json'} do

    resources :users, only: [:index, :show] do
      collection do
        post 'import'
      end
    end

    resources :inventories do
      collection do
        get 'available_amounts'
        get 'reserved_amounts'
        post 'reserve'
        post 'release'
      end
    end

    resources :inventory_models, only: [:index, :show]
    resources :measuring_units, only: [:index, :show]
    resources :skus, only: [:index, :show]
    resources :storages, only: [:index]
  end

  root to: "inventory_operations#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :title, :memberships_attributes

  has_many :memberships, class_name:'GroupMembership', dependent: :destroy
  has_many :users, through: :group_memberships

  validates :title, presence: true, uniqueness: true
  accepts_nested_attributes_for :memberships, allow_destroy: true

  def to_s
    self.title
  end

  def active_memberships
    memberships.reject(&:marked_for_destruction?)
  end

  def user_ids
    active_memberships.map {|m| m.user_id }
  end

  def users
    active_memberships.map { |m| m.user }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter do
    require_user
  end

  before_filter only:[:show, :edit, :update, :destroy] do
    @group = Group.find(params[:id])
  end

  before_filter only:[:new, :create] do
    @group = Group.new
  end

  # GET /groups
  def index
    @groups = Group.order(:title)
  end

  # POST /groups
  def create
    create_or_update
  end

  # PUT /groups/1
  def update
    create_or_update
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url
  end


  private
   def create_or_update
     @group.memberships.reload
     @group.attributes = params[:group]

     if params[:add_users]
       find_avail_users
     end

     if params[:add_ok] && params[:user_ids]
       params[:user_ids].each do |user_id|
         @group.memberships.build(user_id: user_id)
       end
     end

     if params[:ok] && @group.save
       redirect_to @group, notice: t('helpers.notices.saved')
     else
       render action: @group.new_record? ? 'new' : 'edit'
     end
   end

   def find_avail_users
     group_user_ids = @group.user_ids
     @users = group_user_ids.empty? ? User.order(:name) : User.where('id not in (?)', group_user_ids).order(:name)
   end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, html: {class: 'form-horizontal'} do |f| %>
  <%= f.error_messages %>

  <% if params[:add_users] %>
    <%= render 'shared/picker', title: t('shared.picker.pick_users'), items: @users, f: f  %>
  <% end %>

  <div class="control-group">
    <%= f.label :title, "#{t('helpers.attrs.title')}:", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, "#{t('helpers.attrs.description')}:", class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, class: 'text_area' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :users, "#{t('helpers.attrs.users')}:", class: 'control-label' %>
    <div class="controls">
      <%= render 'groups/memberships_form', f: f %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit t('helpers.links.ok'), name: :ok, class: 'btn btn-primary' %>
    <%= link_to t('helpers.links.cancel'), @group, class: 'btn' %>
  </div>
<% end %>

app/views/groups/_membership.html.erb
<tr class="well">
  <td>
    <%= membership.user %>
  </td>
</tr>

app/views/groups/_membership_form.html.erb
<% if f.object.marked_for_destruction? %>
    <% unless f.object.new_record? %>
        <%= f.hidden_field :_destroy, value: true %>
    <% end %>
<% else %>
    <tr class="destroyable well">
      <td>
        <%= f.hidden_field :user_id %>
        <%= f.object.user %>
        <%= f.hidden_field :_destroy %>
        <%= f.button raw('&times;'), class: 'close mark-for-destruction' %>
      </td>
    </tr>
<% end %>

app/views/groups/_memberships.html.erb
<div id="memberships">
  <table class="table table-condensed">
    <tbody>
      <%= render(partial: 'groups/membership', collection: @group.active_memberships) || render('shared/empty')  %>
    </tbody>
  </table>
</div>

app/views/groups/_memberships_form.html.erb
<div id="memberships">
  <table class="table table-condensed">
    <% if @group.active_memberships.empty? %>
        <%= render 'shared/empty' %>
    <% end %>
    <%= f.fields_for :memberships, @group.memberships do |builder| %>
        <%= render 'groups/membership_form', f: builder %>
    <% end %>
  </table>
</div>
<div id="add-users">
  <%= f.button raw("<i class=""icon-plus""></i> <i class=""icon-user""></i>"), name: :add_users, class: 'btn' %>
</div>

app/views/groups/edit.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
  <p class="muted"><%= t('helpers.titles.edit') %></p>
</div>
<%= render partial: 'form' %>

app/views/groups/index.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('helpers.attrs.title') %></th>
      <th><%= t('helpers.attrs.description') %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr data-link="<%= group_path(group) %>">
        <td><%= group.title %></td>
        <td><%= group.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('helpers.links.new'), new_group_path, class: 'btn btn-primary' %>

app/views/groups/new.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
  <p class="muted"><%= t('helpers.titles.new') %></p>
</div>
<%= render partial: 'form' %>

app/views/groups/show.html.erb
<div class="page-header">
  <h3><%=t '.title' %></h3>
</div>

<div class='form-horizontal'>
  <div class="control-group">
    <div class="control-label"><%= t('helpers.attrs.title') %>:</div>
    <div class="controls">
      <span><%= @group.title %></span>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label"><%= t('helpers.attrs.description') %>:</div>
    <div class="controls">
      <span><%= @group.title %></span>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label"><%= t('helpers.attrs.users') %>:</div>
    <div class="controls">
      <%= render 'groups/memberships' %>
    </div>
  </div>
  <div class="form-actions">
    <%= link_to t('helpers.links.index'), groups_path, class: 'btn' %>
    <%= link_to t('helpers.links.edit'), edit_group_path(@group), class: 'btn' %>
    <%= link_to t('helpers.links.destroy'),
                group_path(@group),
                method: :delete,
                data: {confirm: t('helpers.confirmations.destroy')},
                class: 'btn btn-danger' %>
  </div>
</div>