config/routes.rb
SampleApp::Application.routes.draw do

  resources :consumption_reports, only: [:index] do
    collection do
      get 'fmu76'
    end
  end

  resources :vehicles
  resources :vehicle_models
  resources :warehouses
  resources :skus
  resources :inventory_models
  resources :groups
  resources :users
  resources :storages
  resources :user_uploads, only: [:new, :create]
  resources :inventory_reserves do
    member do
      get 'create_order'
    end
  end

  resources :inventory_operations do
    member do
      post 'apply'
    end
  end

  resources :receive_inventories, except: [:index, :destroy]
  resources :write_off_inventories, except: [:index, :destroy] do
    member do
      get 'vehicle_picker'
    end
  end

  resources :take_inventories, except: [:index, :destroy]
  resources :release_inventories, except: [:index, :destroy]

  resource :user_sessions, only: [:create]
  resources :users

  resources :inventories

  resources :measures
  resources :measuring_units
  resources :organizations
  resources :inventory_orders do
    member do
      get 'm11'
      get 'receive'
    end
  end
  resources :barcodes, only: [:show] do
    member do
      get 'draw'
      get 'print'
    end
  end
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  namespace :api, defaults: {format: 'json'} do

    resources :users, only: [:index, :show] do
      collection do
        post 'import'
      end
    end

    resources :inventories do
      collection do
        get 'available_amounts'
        get 'reserved_amounts'
        post 'reserve'
        post 'release'
      end
    end

    resources :inventory_models, only: [:index, :show]
    resources :measuring_units, only: [:index, :show]
    resources :skus, only: [:index, :show]
    resources :storages, only: [:index]
  end

  root to: "inventory_operations#index"

end

app/models/measuring_unit.rb
class MeasuringUnit < ActiveRecord::Base
  attr_accessible :title, :description

  validates :title, presence: true, uniqueness: true

  def to_s
    title
  end
end

app/controllers/api/measuring_units_controller.rb
module Api
  class MeasuringUnitsController < ApiController
    def index
      @measuring_units = MeasuringUnit.order(:title)
    end

    def show
      @measuring_unit = MeasuringUnit.find params[:id]
    end
  end
end

app/controllers/measuring_units_controller.rb
class MeasuringUnitsController < ApplicationController

  before_filter do
    require_user
  end

  before_filter only: [:show, :edit, :update, :destroy] do
    @measuring_unit = MeasuringUnit.find params[:id]
  end

  before_filter only: [:new, :create] do
    @measuring_unit = MeasuringUnit.new
  end

  def index
    @measuring_units = MeasuringUnit.order :title
  end

  def create
    create_or_update
  end

  def update
    create_or_update()
  end

  def create_or_update
    @measuring_unit.attributes = params[:measuring_unit]
    if @measuring_unit.save
      redirect_to @measuring_unit, notice: t('helpers.notices.saved')
    else
      render action: @measuring_unit.new_record? ? 'new' : 'edit'
    end
  end

  def destroy
    @measuring_unit.destroy
    flash[:alert] = t('helpers.notices.destroy.success')
    redirect_to measuring_units_url
  end

end

app/helpers/measuring_units_helper.rb
module MeasuringUnitsHelper
end

app/views/measuring_units/_form.html.erb
<%= form_for @measuring_unit, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :title, "#{t('measuring_units.attrs.title', default: 'Title' )}:", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit t('helpers.links.ok'), class: 'btn btn-primary' %>
    <%= link_to t('helpers.links.cancel'), @measuring_unit, class: 'btn' %>
  </div>
<% end %>

app/views/measuring_units/_measuring_unit.html.erb
<tr data-link="<%= measuring_unit_path(measuring_unit) %>">
  <td><%= measuring_unit.title %></td>
</tr>

app/views/measuring_units/_measuring_units.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= t 'measuring_units.attrs.title' %></th>
  </tr>
  </thead>
  <tbody>
  <% if @measuring_units.blank? %>
      <%= render 'shared/empty', colspan: 1 %>
  <% else %>
      <% @measuring_units.each do |uom| %>
          <%= render partial: 'measuring_unit', object: uom  %>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/measuring_units/edit.html.erb
<%- model_class = MeasuringUnit -%>
<div class="page-header">
  <h3><%= t '.title', default: '%{model}', model: model_class.model_name.human.titleize %></h3>
  <p class="muted"><%= t('helpers.titles.edit') %></p>
</div>
<%= render partial: 'form' %>

app/views/measuring_units/index.html.erb
<%- model_class = MeasuringUnit -%>
<div class="page-header">
  <h3><%= t '.title', default: model_class.model_name.human.pluralize.titleize %></h3>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('measuring_units.attrs.title', default: 'Title') %></th>
    </tr>
  </thead>
  <tbody>
    <% @measuring_units.each do |measuring_unit| %>
      <tr data-link="<%= measuring_unit_path(measuring_unit) %>">
        <td><%= measuring_unit.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('helpers.links.new'), new_measuring_unit_path, class: 'btn btn-primary' %>

app/views/measuring_units/new.html.erb
<%- model_class = MeasuringUnit -%>
<div class="page-header">
  <h3><%= t '.title', default: '%{model}', model: model_class.model_name.human.titleize %></h3>
  <p class="muted"><%= t('helpers.titles.new') %></p>
</div>
<%= render partial: 'form' %>

app/views/measuring_units/show.html.erb
<%- model_class = MeasuringUnit -%>
<div class="page-header">
  <h3><%=t '.title', default: model_class.model_name.human.titleize %></h3>
</div>

<div id="measuring_unit" class="form-horizontal">
      <div class="control-group">
        <div class="control-label"><%= t('measuring_units.attrs.title', default: 'Title') %>:</div>
        <div class="controls">
          <span><%= @measuring_unit.title %></span>
        </div>
      </div>

  <div class="form-actions">
    <%= link_to t('helpers.links.index'), measuring_units_path, class: 'btn'  %>
    <%= link_to t('helpers.links.edit'), edit_measuring_unit_path(@measuring_unit), class: 'btn' %>
    <%= link_to t('helpers.links.destroy'), measuring_unit_path(@measuring_unit),
        method: 'delete',
        data: { confirm: t('helpers.confirmations.destroy', default: 'Are you sure?') },
        class: 'btn btn-danger' %>
  </div>
</div>